"""empty message

Revision ID: 4d2e8ba4f2e2
Revises: c6d0b71e30b0
Create Date: 2021-03-12 13:35:45.480219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2e8ba4f2e2'
down_revision = 'c6d0b71e30b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    #op.alter_column('Artist', 'genres', existing_type=sa.String(length=120), type_=sa.PickleType())

    op.execute('ALTER TABLE "Artist" ALTER COLUMN genres TYPE BYTEA USING genres::bytea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    op.execute('ALTER TABLE "Artist" ALTER COLUMN genres TYPE varchar(120) USING genres::varchar(120)')

    # ### end Alembic commands ###
